### ISSUE TITLE
AffirmSDK/AffirmCreditCard.h file not found

### ISSUE THREAD

**Issue by rzulkoski** [Affirm/affirm-ios-sdk#38]
Version 4.0.16 appears to have introduced a bug where the compiler complains with the following message:

`'AffirmSDK/AffirmCreditCard.h file not found'`

Using:
Carthage v0.32.0
Swift 4.2
Xcode 10.1 (10B61)

**Comment by nandadubey** [comment]
Fixed [here](https://github.com/Affirm/affirm-ios-sdk/commit/1edbf8e11e20d787927b53fdedb23ff01eb6fc30)
