### ISSUE TITLE
Crash on production env, promotional button

### ISSUE THREAD

**Issue by timonchev** [Affirm/affirm-ios-sdk#39]
Hello, I setup Promotional button, for sandbox everything good, but for Production key and Env I have crash in SDK on this line: http://prntscr.com/nibcdi . 

Logs:

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011325d1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001127fb735 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001131a94ec _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00000001132cc541 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x0000000113258c9b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   AffirmSDK                           0x000000010af62a12 -[AffirmErrorResponse dictionary] + 296
	6   AffirmSDK                           0x000000010af60878 __86-[AffirmPromotionalButton configureWithAmount:affirmLogoType:affirmColor:maxFontSize:]_block_invoke + 794
	7   AffirmSDK                           0x000000010af5a427 __59+[__protocolContainer_AffirmClientProtocol_2 send:handler:]_block_invoke_2 + 295
	8   libdispatch.dylib                   0x000000011443d595 _dispatch_call_block_and_release + 12
	9   libdispatch.dylib                   0x000000011443e602 _dispatch_client_callout + 8
	10  libdispatch.dylib                   0x000000011444b99a _dispatch_main_queue_callback_4CF + 1541
	11  CoreFoundation                      0x00000001131c23e9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	12  CoreFoundation                      0x00000001131bca76 __CFRunLoopRun + 2342
	13  CoreFoundation                      0x00000001131bbe11 CFRunLoopRunSpecific + 625
	14  GraphicsServices                    0x0000000116c4d1dd GSEventRunModal + 62
	15  UIKitCore                           0x000000011a2c581d UIApplicationMain + 140
	16  Shiekh Shoes Beta                   0x00000001092d5037 main + 71
	17  libdyld.dylib                       0x00000001144b4575 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException`

**Comment by timonchev** [comment]
response that crashed app: 

{
	"status_code": 400,
	"message": "Invalid merchant API key provided",
	"type": "invalid_request"
}

**Comment by AmyBeall** [comment]
Hello, 
Is this a new integration? If so we have a new SDK we are asking merchants to use at [https://github.com/Affirm/affirm-merchant-sdk-ios/](https://github.com/Affirm/affirm-merchant-sdk-ios/)

I have tested the production API public key for Shiekh Shoes with a production environment for this SDK and everything is working.

If this is an existing integration, please fill out the following form and we will reply quickly [https://docs.affirm.com/Contact_Us/Merchant_Contact_Us](https://docs.affirm.com/Contact_Us/Merchant_Contact_Us)

Thank you

**Comment by timonchev** [comment]
@AmyBeall thanks, I changed key and it's working good now. Yes, we using new SDK now
